pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    product:
                        items:
                            -
                                method: roundCorners
                                arguments:
                                    width: 5
                                    height: 5
                            -
                                method: trim
                                arguments:
                                    tolerance: 10
                            -
                                method: resize
                                arguments:
                                    width: 740
                                    height: 740
                        medias: {  }
                        name: product
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1697020047
                        creationDate: 1695805026
                        preserveAnimation: false
