_pimcore:
    resource: "@PimcoreCoreBundle/config/routing.yaml"

app:
    resource: "../src/Controller/"
    type: annotation

asset_create_image:
    path: /asset/create;
    controller: 'AppBundle\Controller\AssetController::createImageAction'